/*
 * shell.h
 *
 *  Created on: 10.07.2012
 *      Author: bagi
 */

#ifndef SHELL_H_
#define SHELL_H_

#define CMD_SUCCESS 0
#define CMD_ERROR 1

void process_input(char *);

char *shell_error_msg[] = {
		"Invalid directory",
		""
};

enum shell_errors {
	SHELL_DIR_ERROR
};

/**
 *	used to print out a meaningful string to a given error number
 */
char *err2str(int);
void shell_error(int, const char *, ...);

/*
 * concat array of program and arguments generated by parser to a string
 */
char *command2string(int, char **);

/*
 * prints out help of given command
 * use "" to print out general help
 */
void print_cmd_help(char *);

/*
 * included shell commands
 */
int cmd_exit();
int cmd_echo(char *);
int cmd_cd(char *);
int cmd_ls(char *, char *);

#endif /* SHELL_H_ */
